# Copyright (C) 2023 Siemens AG
#
# SPDX-License-Identifier: MIT

$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: package_model
version: 1
display_name: PackageModel
type: command

inputs:
  model_type:
    type: string
  model_name:
    type: string
  model_version:
    type: string
  package_name:
    type: string
  subscription_id:
    type: string
  workspace_name:
    type: string
  resource_group_name:
    type: string

outputs:
  package_path:
    type: uri_file

environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
code: ./../../
command: >-
  python -m ${{inputs.model_type}}.src.package.packaging
  --model_name ${{inputs.model_name}}
  --model_version ${{inputs.model_version}}
  --package_name ${{inputs.package_name}}
  --subscription_id ${{inputs.subscription_id}}
  --workspace_name ${{inputs.workspace_name}}
  --resource_group_name ${{inputs.resource_group_name}}
  --package_path ${{outputs.package_path}}
