name: azure_packaging

channels:
    - conda-forge

dependencies:
    - python=3.8.16
    - pip
    - pip:
        - pandas
        - scikit-learn==1.2.0
        - mlflow==2.4.1
        - azure-ai-ml==0.1.0b6
        - azure-common==1.1.28
        - azure-core==1.26.0
        - azure-identity==1.10.0
        - azure-mgmt-core==1.3.2
        - azure-storage-blob==12.12.0
        - azure-storage-file-datalake==12.7.0
        - azure-storage-file-share==12.8.0
        - mlflow==2.4.1
        - numpy==1.23.5
        - tensorflow==2.7.4
        - -f /tmp
        - seaborn==0.12.2
        - simaticai==1.5.0rc1
        - tsfresh==0.17.0
