# Copyright (C) 2023 Siemens AG
#
# SPDX-License-Identifier: MIT

name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - pandas==2.0.3
    - scikit-learn==1.2.0
    - mlflow==2.8.0
    - azureml-mlflow==1.48.0
    - mldesigner==0.1.0b4
    - azure-ai-ml==1.5.0
    - azure-identity==1.11.0
    - azure-keyvault-secrets==4.7.0
    - tensorflow==2.7.4
    - matplotlib==3.5.1
    - pillow==9.4.0
    - seaborn==0.12.2
