# Copyright (C) 2023 Siemens AG
#
# SPDX-License-Identifier: MIT

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sp_aimmanager_auth_manager'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    workingDirectory: 'devops/pipeline/az_cli_scripts/'
    scriptPath: 'devops/pipeline/az_cli_scripts/create_model_manager_identity.sh'
    arguments: '-S true -s $(subscriptionId) -k $(keyVaultName) -d $(deviceName) -b $(Build.BuildNumber) -h $(iotHubName) -r $(rootCA)'
    addSpnToEnvironment: true
