# Copyright (C) 2023 Siemens AG
#
# SPDX-License-Identifier: MIT

trigger: none

variables:
- group: vg-az-client

pool:
  name: $(AGENT_POOL)

parameters:
 - name: model_type
   displayName: "Model for which the data asset needs to be created"
   default: "state_identifier"
 - name: deploy_env
   displayName: "Deployment Environment"
   default: "dev"

stages:
    - template: templates/variables_template_training_and_packaging.yml
      parameters:
        deploy_env: ${{parameters.deploy_env}}
        model_type: ${{parameters.model_type}}
    - stage: execute_data_asset_creation_job
      displayName: execute_data_asset_creation_job
      dependsOn:
      - variable_generation_training_and_packaging
      variables:
      - template: templates/experiment_variables.yml
      jobs:
      - job: Create_Data_Assets
        steps:
        - template: templates/get_connection_details.yml
        - template: templates/configure_azureml_agent.yml
        - task: AzureCLI@2
          name: create_data_sasets
          displayName: Execute Data Asset Creation
          continueOnError: false
          inputs:
            azureSubscription: $(AZURE_RM_SVC_CONNECTION)
            scriptType: bash
            workingDirectory: $(System.DefaultWorkingDirectory)
            scriptLocation: inlineScript
            failOnStderr: true
            inlineScript: |
              python -m mlops.common.pipeline.data_asset_creation_pipeline \
                --subscription_id $(SUBSCRIPTION_ID) \
                --resource_group_name $(RESOURCE_GROUP_NAME) \
                --workspace_name $(WORKSPACE_NAME) \
                --github_url $(GITHUB_URL) \
                --model_type ${{ parameters.model_type }} \
                --asset_name_ci $(ASSET_NAME_CI) \
                --asset_name_pr $(ASSET_NAME_PR) \
                --cluster_name $(CLUSTER_NAME) \
                --cluster_size $(CLUSTER_SIZE) \
                --cluster_region $(CLUSTER_REGION) \
                --build_reference $(Build.BuildID) \
                --deploy_environment ${{ parameters.deploy_env }}  \
                --experiment_name data_asset_creation \
                --display_name data_asset_creation_${{ parameters.model_type }}_$(Build.BuildID) \
                --environment_name $(ENVIRONMENT_NAME) \
                --conda_path $(CONDA_PATH) \
                --env_base_image_name $(ENV_BASE_IMAGE_NAME)
              echo "The data asset has been created in Azure Data Factory: $(ASSET_NAME_CI) and $(ASSET_NAME_PR)"
