# Copyright (C) 2023 Siemens AG
#
# SPDX-License-Identifier: MIT

trigger: none

variables:
- group: vg-az-client

pool:
  name: $(AGENT_POOL)

parameters:
- name: deploy_env
  type: string
  displayName: "Deployment Environment"
  default: mvp
  values:
  - mvp
  - main
- name: vnet_address_space
  type: string
  displayName: "The address space of the main application virtual network"
  default: "10.0.0.0/16"
- name: integration_subnet_address_space
  type: string
  displayName: "The address space of the integration subnet for the PAAS resources"
  default: "10.0.2.0/24"
- name: training_subnet_address_space
  type: string
  displayName: "The address space of the training subnet for the ML compute"
  default: "10.0.1.0/24"
- name: gateway_subnet_address_space
  type: string
  displayName: "The address space of the VPN gateway"
  default: "10.0.3.0/24"
- name: dns_resolver_subnet_address_space
  type: string
  displayName: "The address space of the Azure Private DNS Resolver"
  default: "10.0.4.0/24"
- name: vpn_client_address_space
  type: string
  displayName: "The address space for the connected VPN clients"
  default: "10.10.0.0/16"

stages:
- stage: Deploy
  displayName: Deploy Infrastructure
  jobs:
  - job: "deploy_terraform"
    displayName: "Deploy Terraform Code"
    steps:
    - task: AzureCLI@2
      name: deploy_terraform
      displayName: "Deploy with terraform"
      inputs:
        scriptLocation: inlineScript
        azureSubscription: $(AZURE_RM_SVC_CONNECTION)
        scriptType: bash
        workingDirectory: $(System.DefaultWorkingDirectory)
        inlineScript: |
          ./scripts/deploy-infra.sh --action apply --source ${{parameters.deploy_env}} --enable-vnet --peer-pipeline --skip-tests \
            --extra-var vnet_address_space=${{parameters.vnet_address_space}} \
            --extra-var integration_subnet_address_space=${{parameters.integration_subnet_address_space}} \
            --extra-var training_subnet_address_range=${{parameters.training_subnet_address_space}} \
            --extra-var gateway_subnet_address_space=${{parameters.gateway_subnet_address_space}} \
            --extra-var dns_resolver_subnet_address_space=${{parameters.dns_resolver_subnet_address_space}} \
            --extra-var vpn_client_address_space=${{parameters.vpn_client_address_space}} \

      env:
        ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
        ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        ARM_TENANT_ID: $(AZURE_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        RESOURCE_GROUP: $(TF_STATE_RESOURCE_GROUP)
        STORAGE_ACCOUNT_NAME: $(TF_STATE_STORAGE_ACCOUNT_NAME)
        CONTAINER_NAME: $(TF_STATE_CONTAINER_NAME)
