trigger: none

schedules:
- cron: "0 3 * * 1"
  displayName: Weekly Monday 3AM Build
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: create_pr
  variables:
    targetBranch: 'main'
    sourceBranch: 'development'
  jobs:
  - job: CreatePR
    steps:
    - bash: az --version
      displayName: 'Show Azure CLI version'

    - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
      displayName: 'Set default Azure DevOps organization and project'

    - bash: |
        az repos pr create --repository $(Build.Repository.Name) \
                          --source-branch $(sourceBranch) \
                          --target-branch $(targetBranch) \
                          --title "Merge Dev into Main" \
                          --description "PR to automatically merge development branch into main created by Azure DevOps pipeline." \
                          --auto-complete true
      displayName: 'Create Pull Request'
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
