# SPDX-FileCopyrightText: 2025 Siemens AG
#
# SPDX-License-Identifier: MIT

name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - pip
  - pip:
    - azure-common==1.1.28
    - azure-core==1.32.0
    - azure-identity==1.20.0
    - azure-keyvault==4.2.0
    - azure-keyvault-secrets==4.9.0
    - azure-monitor-ingestion==1.0.4
    - azure-ai-ml==1.25.0
    - azure-iot-hub==2.6.1
    - azure-eventhub==5.14.0
    - azure-functions==1.21.3
    - azureml-core==1.59.0.post1
    - azureml-mlflow==1.59.0.post1

    # missing from create data asset
    - pyarrow==19.0.1
    - fastparquet==2024.11.0

    # Direct dependencies
    - joblib==1.4.2  # Transitive dependency from simaticai
    - matplotlib==3.9.1
    - numpy==1.24.2  # Transitive dependency from simaticai
    - pandas==2.2.2
    - PyYAML==6.0.1  # Transitive dependency from simaticai
    - scikit-learn==1.5.1
    - seaborn==0.13.2
    - tsfresh==0.20.2
    - mlflow==2.20.3
    - marshmallow==3.26.1

    # Transitive dependencies from simaticai
    - attrs==23.2.0
    - certifi==2024.8.30
    - charset-normalizer==3.3.2
    - coloredlogs==15.0.1
    - flatbuffers==23.5.26
    - humanfriendly==10.0
    - idna==3.7
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - MarkupPy==1.14
    - mpmath==1.3.0
    - onnx==1.16.2
    - onnxruntime==1.17.3
    - packaging==23.2
    - Parsley==1.3
    - protobuf==3.20.3
    - PyYAML==6.0.1
    - referencing==0.32.1
    - requests==2.32.3
    - rpds-py==0.17.1
    - sympy==1.12
    - urllib3==2.2.2

    # Other transitive dependencies
    - cloudpickle==3.0.0
    - contourpy==1.2.1
    - cycler==0.12.1
    - fonttools==4.53.1
    - kiwisolver==1.4.5
    - llvmlite==0.43.0
    - numba==0.60.0
    - patsy==0.5.6
    - pillow==10.4.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - scipy==1.10.1
    - statsmodels==0.14.2
    - stumpy==1.13.0
    - threadpoolctl==3.5.0
    - tqdm==4.66.4
    - tzdata==2024.1
