# Copyright (C) 2023 Siemens AG
#
# SPDX-License-Identifier: MIT

$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_image_classification_model
display_name: TrainImageClassificationModel
version: 1
type: command
inputs:
  training_data:
    type: uri_folder
outputs:
  model_output:
    type: uri_folder
  model_metadata:
    type: uri_file
code: ./../../
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
command: >-
  python -m image_classification.src.train.train
  --training_data ${{inputs.training_data}}
  --model_output ${{outputs.model_output}}
  --model_metadata ${{outputs.model_metadata}}
