# Copyright (C) 2023 Siemens AG
#
# SPDX-License-Identifier: MIT

$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_clustering_model
display_name: TrainClusteringModel
version: 1
type: command
inputs:
  training_data:
    type: uri_folder
outputs:
  model_output:
    type: uri_folder
code: ./../../
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
command: >-
  python -m state_identifier.src.train.train
  --training_data ${{inputs.training_data}}
  --model_output ${{outputs.model_output}}
