# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
#
# SPDX-License-Identifier: MIT

# For adding missing license info for documentation files, use command below
# reuse annotate --copyright "(C) 2025 Siemens AG" --license "MIT" --copyright-style "spdx" --merge-copyrights --recursive --skip-unrecognised ./documentation/

name: Reuse Check

on: [push]

jobs:
  reuse-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Reuse
        run: |
          sudo apt-get update
          sudo apt-get install -y reuse

      - name: Run Reuse lint
        run: reuse lint
